---
# Services handlers

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: not is_macos

- name: restart flask
  systemd:
    name: histomics-flask
    state: restarted
  when: not is_macos

- name: restart ml worker
  systemd:
    name: histomics-ml
    state: restarted
  when: not is_macos
